In [1]:
import pandas as pd
import numpy as np

In [2]:
station_df = pd.read_csv('./station_df.csv')
station_df

,station_id,dustboy_name,tambon,amphoe,province,dustboy_lat,dustboy_lon
0,4,ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่,ช้างม่อย,เมือง,เชียงใหม่,18.785477,98.999660
1,12,Bear Hug Cafe‚ ต.ช้างคลาน อ.เมือง จ.เชียงใหม่,ช้างคลาน,เมือง,เชียงใหม่,18.782900,98.993347
2,13,มช. แคมปัสแม่เหียะ ต.สุเทพ อ.เมือง จ.เชียงใหม่,สุเทพ,เมือง,เชียงใหม่,18.761371,98.931855
3,14,รพ.ฝาง ต.เวียง อ.ฝาง จ.เชียงใหม่,เวียง,ฝาง,เชียงใหม่,19.913293,99.206827
4,16,โรงพยาบาลร้องกวาง ต.ร้องเข็ม อ.ร้องกวาง จ.แพร่,ร้องเข็ม,ร้องกวาง,แพร่,18.307634,100.291242
...,...,...,...,...,...,...,...
250,7126,หน่วยพิทักษ์ป่าสบห้วยผาตั้ง-นาเลา ต.เชียงดาว อ...,เชียงดาว,เชียงดาว,เชียงใหม่,19.413831,98.914826
251,7136,บ้านหนองครก ต.สันทราย อ.พร้าว จ.เชียงใหม่,สันทราย,พร้าว,เชียงใหม่,19.416707,99.158088
252,7156,บ้านผาแดง ต.แม่ปั๋ง อ.พร้าว จ.เชียงใหม่,แม่ปั๋ง,พร้าว,เชียงใหม่,19.221020,99.157458
253,7166,วัดวังตม หมู่บ้านวังตม ต.จางเหนือ อ.แม่เมาะ จ....,จางเหนือ,แม่เมาะ,ลำปาง,18.491297,99.969985
254,7171,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,จางเหนือ,แม่เมาะ,ลำปาง,18.357949,99.892538

In [3]:
start_date = pd.to_datetime('2026-04-30')
dates = pd.date_range(start=start_date, periods=7)

all_days = []

for current_day in dates:
    temp_df = station_df.copy()
    temp_df['pm25'] = np.random.randint(20, 100, size=len(station_df))
    temp_df['date'] = current_day.date()
    all_days.append(temp_df)

# 3. Concat them all together at once
pred_station_df = pd.concat(all_days, ignore_index=True)
pred_station_df

,station_id,dustboy_name,tambon,amphoe,province,dustboy_lat,dustboy_lon,pm25,date
0,4,ไนท์บาร์ซาร์ ต.ช้างม่อย อ.เมือง จ. เชียงใหม่,ช้างม่อย,เมือง,เชียงใหม่,18.785477,98.999660,67,2026-04-30
1,12,Bear Hug Cafe‚ ต.ช้างคลาน อ.เมือง จ.เชียงใหม่,ช้างคลาน,เมือง,เชียงใหม่,18.782900,98.993347,26,2026-04-30
2,13,มช. แคมปัสแม่เหียะ ต.สุเทพ อ.เมือง จ.เชียงใหม่,สุเทพ,เมือง,เชียงใหม่,18.761371,98.931855,29,2026-04-30
3,14,รพ.ฝาง ต.เวียง อ.ฝาง จ.เชียงใหม่,เวียง,ฝาง,เชียงใหม่,19.913293,99.206827,41,2026-04-30
4,16,โรงพยาบาลร้องกวาง ต.ร้องเข็ม อ.ร้องกวาง จ.แพร่,ร้องเข็ม,ร้องกวาง,แพร่,18.307634,100.291242,35,2026-04-30
...,...,...,...,...,...,...,...,...,...
1780,7126,หน่วยพิทักษ์ป่าสบห้วยผาตั้ง-นาเลา ต.เชียงดาว อ...,เชียงดาว,เชียงดาว,เชียงใหม่,19.413831,98.914826,62,2026-05-06
1781,7136,บ้านหนองครก ต.สันทราย อ.พร้าว จ.เชียงใหม่,สันทราย,พร้าว,เชียงใหม่,19.416707,99.158088,86,2026-05-06
1782,7156,บ้านผาแดง ต.แม่ปั๋ง อ.พร้าว จ.เชียงใหม่,แม่ปั๋ง,พร้าว,เชียงใหม่,19.221020,99.157458,62,2026-05-06
1783,7166,วัดวังตม หมู่บ้านวังตม ต.จางเหนือ อ.แม่เมาะ จ....,จางเหนือ,แม่เมาะ,ลำปาง,18.491297,99.969985,79,2026-05-06
1784,7171,วัดปงแท่น หมู่บ้านปงแท่น ต.จางเหนือ อ.แม่เมาะ ...,จางเหนือ,แม่เมาะ,ลำปาง,18.357949,99.892538,49,2026-05-06

In [4]:
station_df_amphoe = pred_station_df[['amphoe', 'province', 'dustboy_lat', 'dustboy_lon', 'pm25', 'date']].groupby(by = ['date', 'province', 'amphoe'], as_index=False).mean()
station_df_amphoe = station_df_amphoe[station_df_amphoe['province'] != "ชียงใหม่"]
station_df_amphoe = station_df_amphoe[station_df_amphoe['amphoe'] != "มือง"]
station_df_amphoe.to_csv('./pm_mock.csv', index = False)
station_df_amphoe

           date    province      amphoe  dustboy_lat  dustboy_lon       pm25
1    2026-04-30        น่าน    ทุ่งช้าง    19.520638   100.924948  76.000000
2    2026-04-30        น่าน    ท่าวังผา    19.135390   100.785690  51.000000
3    2026-04-30        น่าน      นาน้อย    18.340077   100.713176  25.000000
4    2026-04-30        น่าน     นาหมื่น    18.192573   100.581634  70.000000
5    2026-04-30        น่าน    บ้านหลวง    18.851955   100.436006  48.000000
..          ...         ...         ...          ...          ...        ...
660  2026-05-06  แม่ฮ่องสอน         ปาย    19.356415    98.433473  44.250000
661  2026-05-06  แม่ฮ่องสอน       สบเมย    17.964319    97.930964  54.500000
662  2026-05-06  แม่ฮ่องสอน       เมือง    19.299731    97.973912  79.000000
663  2026-05-06  แม่ฮ่องสอน   แม่ลาน้อย    18.458245    97.941862  55.666667
664  2026-05-06  แม่ฮ่องสอน  แม่สะเรียง    18.062980    97.917651  78.000000

[644 rows x 6 columns]

In [5]:
np.random.seed(42)
patient_data = []
unique_loc = station_df_amphoe[['province', 'amphoe']].drop_duplicates()

for _, row in unique_loc.iterrows():
    num_patients = np.random.randint(3, 8)  # Random 3-7 patients per station
    for i in range(num_patients):
        patient_data.append({
            'amphoe': row['amphoe'],
            'province': row['province'],
            'cid': f"1-{np.random.randint(1000, 9999)}-{np.random.randint(10000, 99999)}",
            'age': np.random.randint(5, 85),
            'sex': np.random.choice(['M', 'F']),
        })

# Create the final dataframe
df_patients = pd.DataFrame(patient_data)
df_patients.to_csv('./patient_mock.csv', index = False)
df_patients

         amphoe    province           cid  age sex
0      ทุ่งช้าง        น่าน  1-1860-86820   79   M
1      ทุ่งช้าง        น่าน  1-9322-77221   57   F
2      ทุ่งช้าง        น่าน  1-7949-77969   68   F
3      ทุ่งช้าง        น่าน  1-7420-93104   80   F
4      ทุ่งช้าง        น่าน  1-7396-35658   46   F
..          ...         ...           ...  ...  ..
453  แม่สะเรียง  แม่ฮ่องสอน  1-5356-23760   44   F
454  แม่สะเรียง  แม่ฮ่องสอน  1-8062-62233   71   F
455  แม่สะเรียง  แม่ฮ่องสอน  1-1269-86367   78   M
456  แม่สะเรียง  แม่ฮ่องสอน  1-6897-86619    5   M
457  แม่สะเรียง  แม่ฮ่องสอน  1-6895-89530   80   M

[458 rows x 5 columns]